"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Label } from "@/components/ui/primitives";

export interface NewsItem {
  id: string;
  type: string;
  description: string;
  importance: string;
  season: number;
  teamIds: string[];
  /**
   * Set on rows generated by an executed trade (the deal itself, plus its fan
   * reaction and icon-departure fallout). Present only for trades made after
   * cap snapshots were introduced; older rows stay unlinked rather than
   * pointing at an outcome page with no evidence to show.
   */
  tradeId?: string | null;
}

const CATEGORIES = [
  "ALL",
  "TRADE",
  "SIGNING",
  "STAFF",
  "ALL_STAR",
  "ROTATION",
  "DRAFT",
  "RETIREMENT",
  "INJURY",
  "AWARD",
  "GAME_MILESTONE",
  "WIN_STREAK",
  "GAME_RESULT",
  "OWNERSHIP_MESSAGE",
  "MORALE",
  "FINANCES",
] as const;

const CATEGORY_LABEL: Record<(typeof CATEGORIES)[number], string> = {
  ALL: "All",
  TRADE: "Trades",
  SIGNING: "Free Agency",
  STAFF: "Staff",
  ALL_STAR: "All-Star",
  ROTATION: "Rotation",
  DRAFT: "Draft",
  RETIREMENT: "Retirements",
  INJURY: "Injuries",
  AWARD: "Awards",
  GAME_MILESTONE: "Milestones",
  WIN_STREAK: "Streaks",
  GAME_RESULT: "Games",
  OWNERSHIP_MESSAGE: "Ownership",
  MORALE: "Morale",
  FINANCES: "Finances",
};

// Every other category maps 1:1 to a single TransactionType - STAFF and
// ALL_STAR are the exceptions, each grouping several related types under
// one filter pill rather than adding a pill per type for what's really one
// concept to a reader.
const CATEGORY_TYPES: Record<(typeof CATEGORIES)[number], string[] | null> = {
  ALL: null,
  TRADE: ["TRADE"],
  SIGNING: ["SIGNING"],
  STAFF: ["STAFF_HIRE", "STAFF_FIRE"],
  ALL_STAR: ["ALL_STAR_SELECTION", "ALL_STAR_SNUB", "ALL_STAR_RESULT"],
  ROTATION: ["ROTATION_CHANGE"],
  DRAFT: ["DRAFT_LOTTERY", "DRAFT_SELECTION"],
  RETIREMENT: ["RETIREMENT"],
  INJURY: ["INJURY"],
  AWARD: ["AWARD"],
  GAME_MILESTONE: ["GAME_MILESTONE"],
  WIN_STREAK: ["WIN_STREAK"],
  GAME_RESULT: ["GAME_RESULT"],
  OWNERSHIP_MESSAGE: ["OWNERSHIP_MESSAGE"],
  MORALE: ["PLAYER_MORALE"],
  FINANCES: ["FINANCIAL_REPORT", "FRANCHISE_MILESTONE"],
};

const TYPE_LABEL: Record<string, string> = {
  TRADE: "Trade",
  SIGNING: "Signing",
  STAFF_HIRE: "Staff Hire",
  STAFF_FIRE: "Staff Fire",
  ALL_STAR_SELECTION: "All-Star",
  ALL_STAR_SNUB: "All-Star Snub",
  ALL_STAR_RESULT: "All-Star Weekend",
  ROTATION_CHANGE: "Rotation",
  DRAFT_LOTTERY: "Draft Lottery",
  DRAFT_SELECTION: "Draft",
  RETIREMENT: "Retirement",
  INJURY: "Injury",
  OWNERSHIP_MESSAGE: "Ownership",
  GAME_MILESTONE: "Milestone",
  WIN_STREAK: "Streak",
  GAME_RESULT: "Game",
  AWARD: "Award",
  PLAYER_MORALE: "Morale",
  FINANCIAL_REPORT: "Finances",
  FRANCHISE_MILESTONE: "Franchise Value",
};

function seasonLabel(season: number): string {
  return `${season}-${(season + 1).toString().slice(-2)}`;
}

function pillClass(active: boolean): string {
  return `rounded-[2px] border px-2.5 py-1 text-[11px] font-semibold tracking-[0.09em] uppercase transition-colors duration-120 ${
    active
      ? "border-team-accent bg-team-accent text-team-accent-ink"
      : "border-rule text-ink-muted hover:bg-raised hover:text-ink"
  }`;
}

/**
 * One filed row on the wire.
 *
 * Four registers, mapped to the importance the engine already assigns rather
 * than an invented one. Measured against the real data: BREAKING is 11 rows
 * out of 5,545 (0.2%), MAJOR 7%, and MINOR/STANDARD the remaining 90%. So the
 * frame breaks almost never - which is what makes it mean something when it
 * does. Routine rows get *tighter* than before, not louder.
 */
function WireRow({
  item,
  leagueId,
  isMine,
}: {
  item: NewsItem;
  leagueId: string;
  isMine: boolean;
}) {
  const breaking = item.importance === "BREAKING";
  const major = item.importance === "MAJOR";
  const minor = item.importance === "MINOR";

  // Your own franchise's rows carry the team accent on their leading rule.
  // Meaningful (this is your save), not category decoration.
  const leadRule = isMine ? "border-l-team-accent" : "border-l-transparent";

  if (breaking) {
    return (
      <article className="border-t-2 border-team-accent bg-field px-4 py-5 sm:px-5">
        <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
          <Label tone="accent">Breaking</Label>
          <span className="text-[11px] font-semibold tracking-[0.09em] text-ink-muted uppercase">
            {TYPE_LABEL[item.type] ?? item.type}
          </span>
        </div>
        <p className="mt-3 text-[clamp(1.125rem,1.8vw,1.375rem)] leading-snug font-semibold text-ink">
          {item.description}
        </p>
        {item.tradeId && (
          <Link
            href={`/leagues/${leagueId}/trades/${item.tradeId}`}
            className="mt-3 inline-block text-[11px] font-semibold tracking-[0.09em] text-team-accent uppercase underline decoration-rule underline-offset-4"
          >
            See the deal
          </Link>
        )}
      </article>
    );
  }

  return (
    <article
      className={`flex gap-x-4 border-b border-l-2 border-b-hairline ${leadRule} py-2.5 pr-2 pl-3 transition-colors duration-120 hover:bg-raised`}
    >
      <span
        className={`w-28 shrink-0 pt-0.5 text-[11px] font-semibold tracking-[0.09em] uppercase ${
          major ? "text-ink" : "text-ink-muted"
        }`}
      >
        {TYPE_LABEL[item.type] ?? item.type}
      </span>
      <p
        className={`min-w-0 flex-1 ${
          major
            ? "text-[17px] leading-snug font-medium text-ink"
            : minor
              ? "text-[15px] leading-snug text-ink-muted"
              : "text-[15px] leading-snug text-ink"
        }`}
      >
        {item.description}
        {item.tradeId && (
          <>
            {" "}
            <Link
              href={`/leagues/${leagueId}/trades/${item.tradeId}`}
              className="text-[11px] font-semibold tracking-[0.09em] whitespace-nowrap text-team-accent uppercase underline decoration-rule underline-offset-4"
            >
              See the deal
            </Link>
          </>
        )}
      </p>
    </article>
  );
}

/**
 * All filtering happens client-side over an already-fetched (capped at
 * 200) list - same "filter a preloaded list" convention as DraftExperience,
 * not a server round-trip per click, since the underlying dataset is
 * already small and bounded.
 *
 * THE WIRE - Ledger. Rows are ruled lines filed under a season, not a stack
 * of identical cards. `createdAt` is deliberately never shown: simulation
 * runs in bursts, so 400-800 rows share the same real-world minute and a
 * clock time would be fake precision. Season is the only honest time unit.
 */
export function NewsFeed({
  transactions,
  userTeamId,
  leagueId,
}: {
  transactions: NewsItem[];
  userTeamId: string | null;
  leagueId: string;
}) {
  const [category, setCategory] = useState<(typeof CATEGORIES)[number]>("ALL");
  const [myTeamOnly, setMyTeamOnly] = useState(false);
  const [search, setSearch] = useState("");

  const filtered = useMemo(() => {
    const query = search.trim().toLowerCase();
    return transactions.filter((t) => {
      if (category !== "ALL" && !CATEGORY_TYPES[category]!.includes(t.type)) return false;
      if (myTeamOnly && (!userTeamId || !t.teamIds.includes(userTeamId))) return false;
      if (query && !t.description.toLowerCase().includes(query)) return false;
      return true;
    });
  }, [transactions, category, myTeamOnly, search]);

  /** Filed under the season it happened in - the wire's own structure. */
  const bySeason = useMemo(() => {
    const groups = new Map<number, NewsItem[]>();
    for (const item of filtered) {
      const list = groups.get(item.season) ?? [];
      list.push(item);
      groups.set(item.season, list);
    }
    return [...groups.entries()].sort((a, b) => b[0] - a[0]);
  }, [filtered]);

  return (
    <div className="grid grid-cols-1 gap-8 lg:grid-cols-[1fr_240px] lg:items-start">
      {/* THE WIRE ITSELF */}
      <div className="min-w-0 lg:order-1">
        <p
          aria-live="polite"
          className="text-[11px] font-semibold tracking-[0.09em] text-ink-muted uppercase"
        >
          {filtered.length} of {transactions.length} filed
        </p>

        {filtered.length === 0 ? (
          <div className="mt-4 border-t border-rule bg-field p-8 text-center">
            <p className="text-[15px] text-ink-muted">No stories match these filters.</p>
          </div>
        ) : (
          <div className="mt-4 space-y-10">
            {bySeason.map(([season, items]) => (
              <section key={season}>
                <div className="flex items-baseline justify-between gap-3 border-b border-rule-strong pb-2">
                  <h2 className="font-mono text-[15px] font-medium tabular-nums text-ink">
                    {seasonLabel(season)}
                  </h2>
                  <span className="font-mono text-[11px] tabular-nums text-ink-muted">
                    {items.length}
                  </span>
                </div>
                <div className="mt-1">
                  {items.map((item) => (
                    <WireRow
                      key={item.id}
                      item={item}
                      leagueId={leagueId}
                      isMine={Boolean(userTeamId && item.teamIds.includes(userTeamId))}
                    />
                  ))}
                </div>
              </section>
            ))}
          </div>
        )}
      </div>

      {/* THE DESK. Filters stay put while the wire scrolls. */}
      <aside className="lg:sticky lg:top-6 lg:order-2">
        <div className="border-t border-rule bg-field p-4">
          <Label>Search</Label>
          <input
            type="search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Any name or phrase"
            className="mt-2 w-full rounded-[2px] border border-rule bg-raised px-3 py-1.5 text-[15px] text-ink transition-colors duration-120 placeholder:text-ink-muted/60 focus:border-rule-strong"
          />

          {userTeamId && (
            <div className="mt-4">
              <Label>Scope</Label>
              <button
                type="button"
                onClick={() => setMyTeamOnly((v) => !v)}
                className={`mt-2 ${pillClass(myTeamOnly)}`}
              >
                My franchise
              </button>
            </div>
          )}

          <div className="mt-4">
            <Label>Category</Label>
            <div className="mt-2 flex flex-wrap gap-1.5">
              {CATEGORIES.map((c) => (
                <button
                  key={c}
                  type="button"
                  onClick={() => setCategory(c)}
                  className={pillClass(category === c)}
                >
                  {CATEGORY_LABEL[c]}
                </button>
              ))}
            </div>
          </div>
        </div>
      </aside>
    </div>
  );
}
